# Generated by Django 3.2.3 on 2021-05-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mandy', '0002_auto_20210524_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.IntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
