# Generated by Django 3.2.3 on 2021-05-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mandy', '0003_auto_20210524_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.CharField(max_length=20),
        ),
    ]
