# Generated by Django 3.2.3 on 2021-05-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mandy', '0004_auto_20210524_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
